version: '3'

services: 
  api:
    build: .
    environment:
      - BIND_ADDR=${BIND_ADDR:-0.0.0.0:8080}
      - RUST_LOG=${LOG_LEVEL:-info}
    ports:
      - "${HTTP_PORT:-8080}:8080"
    restart: always
    container_name: "rust-api-service"
    networks:
      - "api_main_net"

networks:
  api_main_net:
    driver: bridge

